#!/bin/sh
#
# PROVIDE: nzbdrone
# REQUIRE: mono
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# nzbdrone_enable (bool):	Set to NO by default.
#			Set it to YES to enable it.
# nzbdrone_data_dir:	Directory where nzbdrone configuration
#			data is stored.
#			Default: /home/${nzbdrone_user}/.config/NzbDrone
# nzbdrone_user:	The user account nzbdrone daemon runs as what
#			you want it to be. It uses 'nobody' user by
#			default. Do not sets it as empty or it will run
#			as root.
# nzbdrone_group:	The group account nzbdrone daemon runs as what
#			you want it to be. It uses 'user' group by
#			default. Do not sets it as empty or it will run
#			as wheel.

. /etc/rc.subr
name="nzbdrone"
rcvar="${name}_enable"
load_rc_config $name
start_postcmd="${name}_poststart"
pidfile="/var/run/${name}.pid"
stop_postcmd="${name}_poststop"


: ${nzbdrone_enable:="NO"}
: ${nzbdrone_user:="nobody"} #NOTE: DO NOT RUN AS ROOT, IT WILL BURN YOUR HOUSE DOWN AND RAPE YOUR CAT!
: ${nzbdrone_group:="user"}
: ${nzbdrone_dir:="/opt/NzbDrone"}
: ${nzbdrone_data_dir:="/home/${nzbdrone_user}/.config/NzbDrone"}
: ${nzbdrone_log:="/var/log/nzbdrone.log"}

command="/usr/local/bin/mono"
command_args="/opt/NzbDrone/NzbDrone.exe >$nzbdrone_log 2>&1 &"
nzbdrone_poststart()
{
        MONOSERVER_PID=$(ps ax | grep "NzbDrone.exe" | grep -v grep | awk '{print $1}')
        if [ -f $pidfile ]; then
                rm $pidfile
        fi
        if [ -n $MONOSERVER_PID ]; then
                echo $MONOSERVER_PID > $pidfile
        fi
}
nzbdrone_poststop()
{
        rm $pidfile
}
run_rc_command "$1"
