#!/bin/sh
#
# PROVIDE: nzbdrone
# REQUIRE: NETWORKING SERVERS DAEMON ldconfig resolv
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# nzbdrone_enable (bool):	Set to NO by default.
#			Set it to YES to enable it.
# nzbdrone_data_dir:	Directory where nzbdrone configuration
#			data is stored.
#			Default: /home/${nzbdrone_user}/.config/NzbDrone
# nzbdrone_user:	The user account nzbdrone daemon runs as what
#			you want it to be. It uses '%%USER%%' user by
#			default. Do not sets it as empty or it will run
#			as root.
# nzbdrone_group:	The group account nzbdrone daemon runs as what
#			you want it to be. It uses '%%GROUP%%' group by
#			default. Do not sets it as empty or it will run
#			as wheel.

. /etc/rc.subr
name="nzbdrone"
rcvar="${name}_enable"
load_rc_config $name
start_postcmd="${name}_poststart"
pidfile="/var/run/${name}.pid"
stop_postcmd="${name}_poststop"


: ${nzbdrone_enable:="NO"}
: ${nzbdrone_user:="nzbdrone"} #Note: Do not use root, and don't use a user without a home directory. If in doubt, either create a new user "nzbdrone" with a standard home directory "/home/nzbdrone/" or use the user that your nzb-app uses, sabnzbget or whatever.
: ${nzbdrone_group:="nzbdrone"}
: ${nzbdrone_dir:="/opt/NzbDrone"}
: ${nzbdrone_data_dir:="/home/${nzbdrone_user}/.config/NzbDrone"}
: ${nzbdrone_log:="/var/log/nzbdrone.log"}

command="/usr/local/bin/mono"
command_args="$nzbdrone_dir/NzbDrone.exe >$nzbdrone_log 2>&1 &"
nzbdrone_poststart()
{
	echo $rc_pid> $pidfile
}
nzbdrone_poststop()
{
        rm $pidfile
}
run_rc_command "$1"
